FROM python:3.13-alpine

WORKDIR /app

# Copia primeiro o arquivo de dependências para aproveitar o cache do Docker
COPY requirements.txt .

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do código da aplicação
COPY . .

# Cria um usuário não-root para rodar a aplicação
RUN adduser -D myuser
USER myuser

CMD ["python", "app.py"]